askPassScript: |-
  #!/bin/bash
  set -u
  echo ${VCS_TOKEN}

# add repos in following format:
# repos: |-
#  - org/repo-name
repos: |
  - org/repo-name

steward:
  # provide values for the following
  vcsLogin:
  vcsToken:
  gitAuthorName:
  gitAuthorEmail:

# If you need to provide Nexus credentials, uncomment the below lines and provide proper credentials
# credentialsSbt: |
#  credentials += Credentials("Some Nexus Repository Manager", "my.artifact.repo.net", "admin", "admin123")

# If empty, the chart will create the secret containing the vcs token.
# If not empty - the already existing secret is used.
# The secret should have a field names VCS_TOKEN
existingSecretName:

image:
  repository: fthomas/scala-steward
  tag: latest
  pullPolicy: IfNotPresent

cron:
  interval: "@daily"
  restartPolicy: OnFailure

args:
  - --workspace
  - "/opt/scala-steward/workspace"
  - --repos-file
  - "/opt/config_values/repos.md"
  - --git-author-name
  - "$(GIT_AUTHOR_NAME)"
  - --git-author-email
  - "$(GIT_AUTHOR_EMAIL)"
  - --vcs-api-host
  - "https://api.github.com"
  - --vcs-login
  - "$(VCS_LOGIN)"
  - --git-ask-pass
  - "/opt/config_values/git_ask_pass_script.sh"
  - --do-not-fork

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClassName: standard

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
