name: Scala Steward Helm Chart CI/CD

on:
  push:
    paths:
      - 'helm/**'
  pull_request:
    paths:
      - 'helm/**'

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up Helm
        uses: azure/setup-helm@v1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Setup chart testing
        uses: helm/chart-testing-action@v2.0.1
      - name: Run chart-testing (lint)
        run: ct lint --chart-dirs helm --all

  publish:
    needs: lint
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Publish helm chart
        uses: stefanprodan/helm-gh-pages@v1.2.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          charts_dir: helm
          charts_url: https://softwaremill.github.io/sml-helm-public-repo
          owner: softwaremill
          repository: sml-helm-public-repo
          helm_version: 3.4.1
          linting: off
