{{- if .Values.credentialsSbt }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "steward.fullname" . }}-credentials-sbt
data:
  credentials.sbt: |-
    {{- .Values.credentialsSbt | b64enc | nindent 4 }}
{{- end }}