{{- if not .Values.existingSecretName }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "steward.fullname" . }}
data:
  VCS_TOKEN: {{ .Values.steward.vcsToken | quote | b64enc  }}
{{- end }}

